name: dev-builds
on:
  push:
    branches:
      - 'dev'
  pull_request:
  workflow_dispatch:

jobs:

  windows-builds:
    runs-on: windows-latest
    strategy:
      matrix:
        rid: [ win-x86, win-x64, win-arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      
      - name: Dotnet publish
        run: dotnet publish -r ${{matrix.rid}} --self-contained -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --output buildDir src/Platforms/HolyClient.Desktop
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: buildDir/HolyClient.Desktop.exe
          name: HolyClient.Desktop-${{matrix.rid}}
          if-no-files-found: error
          
          
  linux-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [linux-x64, linux-musl-x64,linux-musl-arm64,linux-arm,linux-arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Dotnet publish
        run: dotnet publish -r ${{matrix.rid}} --self-contained -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --output buildDir src/Platforms/HolyClient.Desktop

      - run: chmod +x ./buildDir/HolyClient.Desktop
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: buildDir/HolyClient.Desktop
          name: HolyClient.Desktop-${{matrix.rid}}
          if-no-files-found: error
  
  macos-builds:
    runs-on: macos-latest
    strategy:
      matrix:
        rid: [osx-x64, osx-arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Dotnet publish
        run: dotnet publish -r ${{matrix.rid}} --self-contained -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --output buildDir src/Platforms/HolyClient.Desktop

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: buildDir/HolyClient.Desktop
          name: HolyClient.Desktop-${{matrix.rid}}
          if-no-files-found: error