name: dev-builds
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'dev'
  pull_request:
  workflow_dispatch:

jobs:

  basic:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - run: dotnet --version
        
      - name: set shell script permissions
        if: ${{ matrix.os != 'windows-latest'}}
        run: chmod +x ./build.sh

      - name: build (Unix)
        if: ${{ matrix.os != 'windows-latest'}}
        run: ./build.sh DevBuild --Configuration Release --Runtime linux-x64

      - name: build (Windows)
        if: ${{ matrix.os == 'windows-latest'}}
        run: .\build.ps1 DevBuild --Configuration Release --Runtime win-x64