name: dev-builds
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'dev'
  pull_request:
  workflow_dispatch:

jobs:

  basic:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - run: dotnet --version
      
      - name: Install Pupnet and dpkg
        if: ${{ matrix.os == 'ubuntu-latest'}}
        run: |
          dotnet tool install -g KuiperZone.PupNet
          sudo apt install dpkg         
      
      - name: Run pupnet
        if: ${{ matrix.os == 'ubuntu-latest'}}
        run: pupnet --runtime linux-x64 --kind deb