name: dev-builds
on:
  push:
    branches:
      - 'dev'
  pull_request:
  workflow_dispatch:

jobs:

  windows-builds:
    runs-on: windows-latest
    strategy:
      matrix:
        rid: [ win-x86, win-x64, win-arm64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - run: dotnet --version
      
      - name: Dotnet publish
        run: dotnet publish -r ${{matrix.rid}} --self-contained -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --output buildDir src/Platforms/HolyClient.Desktop
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: buildDir/HolyClient.Desktop
          name: HolyClient.Desktop-${{matrix.rid}}          